name: fairshare_app
description: "Offline-first group expense sharing app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management & Data
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.33
  
  # Navigation & Routing
  go_router: ^15.1.1
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.3.0
  
  # UI & Theming
  flex_color_scheme: ^8.2.0
  
  # Utilities
  path_provider: ^2.1.5
  path: ^1.9.1
  result_dart: ^2.1.0
  logger: ^2.5.0
  connectivity_plus: ^6.1.4
  currency_picker: ^2.0.21
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  
dev_dependencies:
  # Code Generation
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  drift_dev: ^2.26.1
  
  # Analysis & Linting
  riverpod_lint: ^2.6.5
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true