// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmK41s1Kz8mQFpP8CJ90dJEAgGGUWej0E',
    appId: '1:678204431234:android:3ba519bd88e063b3accd9b',
    messagingSenderId: '678204431234',
    projectId: 'friendsfairshare',
    storageBucket: 'friendsfairshare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa0zij-qN23mWpXvO1f4rY4ZFvo4Lh_Rc',
    appId: '1:678204431234:ios:a053999abca6d64faccd9b',
    messagingSenderId: '678204431234',
    projectId: 'friendsfairshare',
    storageBucket: 'friendsfairshare.firebasestorage.app',
    androidClientId: '678204431234-1fmujb2ehsckb6kqr3rfhrduoffdtc88.apps.googleusercontent.com',
    iosClientId: '678204431234-d95t14gn80j6r6sa42243u79cr9btiph.apps.googleusercontent.com',
    iosBundleId: 'com.fairshare.fairshareApp',
  );
}
